apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  USER: root
  PASSWORD: password_mysql
  DATABASE_URL: mysql://mysql:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
 
