apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-app-javadb
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002 # 30000 ~ 32767
  selector:
    app: pod-app-javadb
    
