apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-replicaset
spec:
  template:
    metadata:
      name: pod-app-javadb
      labels:
        app: pod-app-javadb
    spec:
      containers:
        - name: container-pod-app-javadb
          image: ffaneto/crud-java-login:v0.0.1
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-app-javadb
